{{- if .Values.networkPolicy.enabled }}
# ─── Uptime Kuma → allow ingress from Ingress controller + egress to MySQL + DNS ─
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic to the web UI from anywhere inside the cluster
    # (tighten by restricting to ingress-controller namespace labels if desired).
    - ports:
        - port: 3001
          protocol: TCP
    {{- with .Values.networkPolicy.additionalIngressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- if .Values.mysql.enabled }}
    # Allow outbound to MySQL on port 3306.
    # Port-only rule (no 'to' podSelector) ensures ClusterIP traffic isn't
    # blocked — some CNIs don't match podSelector egress rules against
    # kube-proxy DNAT'd ClusterIP destinations.
    - ports:
        - port: {{ .Values.mysql.service.port }}
          protocol: TCP
    {{- end }}
    # Allow outbound HTTPS for external monitoring checks
    - ports:
        - port: 443
          protocol: TCP
        - port: 80
          protocol: TCP
    {{- with .Values.networkPolicy.additionalEgressRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- if .Values.mysql.enabled }}
# ─── MySQL — only accessible from Uptime Kuma pod ────────────────────────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "uptime-kuma.mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.mysql.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "uptime-kuma.mysql.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "uptime-kuma.selectorLabels" . | nindent 14 }}
      ports:
        - port: 3306
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
{{- end }}
