{{/*
  MySQL root + app credentials secret.
  Only created when NOT using an existingSecret.

  Password generation strategy:
  - On first install: randAlphaNum generates a random 32-char password.
  - On subsequent upgrades: lookup retrieves the existing secret so the
    password is preserved. Without this, every `helm upgrade` would
    regenerate the password and break the running database.
*/}}
{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
{{- $mysqlSecretName := include "uptime-kuma.mysql.secretName" . }}
{{- $existingMysqlSecret := lookup "v1" "Secret" .Release.Namespace $mysqlSecretName }}

{{- $rootPassword := "" }}
{{- $appPassword := "" }}

{{- if $existingMysqlSecret }}
  {{/* Secret already exists — decode and reuse current passwords. */}}
  {{- $rootPassword = index $existingMysqlSecret.data "mysql-root-password" | b64dec }}
  {{- $appPassword  = index $existingMysqlSecret.data "mysql-password"      | b64dec }}
{{- else }}
  {{/* First install — use provided values or generate random passwords. */}}
  {{- $rootPassword = .Values.mysql.auth.rootPassword | default (randAlphaNum 32) }}
  {{- $appPassword  = .Values.mysql.auth.password     | default (randAlphaNum 32) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $mysqlSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.mysql.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  mysql-root-password: {{ $rootPassword | b64enc | quote }}
  mysql-password: {{ $appPassword | b64enc | quote }}
{{- end }}
---
{{/*
  App-facing DB credentials secret used by the Uptime Kuma deployment.
  Mirrors the mysql-password (or externalDatabase.password) so both secrets
  stay in sync using the same password value.
*/}}
{{- if not (or .Values.mysql.auth.existingSecret .Values.externalDatabase.existingSecret) }}
{{- $dbSecretName := printf "%s-db-credentials" (include "uptime-kuma.fullname" .) }}

{{- $dbPassword := "" }}
{{- if .Values.mysql.enabled }}
  {{- $mysqlSecretName := include "uptime-kuma.mysql.secretName" . }}
  {{- $existingMysqlSecret := lookup "v1" "Secret" .Release.Namespace $mysqlSecretName }}
  {{- if $existingMysqlSecret }}
    {{/* Reuse whatever is already in the mysql secret. */}}
    {{- $dbPassword = index $existingMysqlSecret.data "mysql-password" | b64dec }}
  {{- else }}
    {{/* First install — fall back to provided value or generate. */}}
    {{- $dbPassword = .Values.mysql.auth.password | default (randAlphaNum 32) }}
  {{- end }}
{{- else }}
  {{- $dbPassword = .Values.externalDatabase.password }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  db-password: {{ $dbPassword | b64enc | quote }}
{{- end }}
