{{/*
  MySQL root + app credentials secret — only created when NOT using an existingSecret.
*/}}
{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.mysql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.mysql.labels" . | nindent 4 }}
  annotations:
    # Helm will not update these values on upgrade — rotate manually.
    helm.sh/resource-policy: keep
type: Opaque
data:
  mysql-root-password: {{ required "mysql.auth.rootPassword is required (or provide mysql.auth.existingSecret)" .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ required "mysql.auth.password is required (or provide mysql.auth.existingSecret)" .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
---
{{/*
  App-facing DB credentials secret — only when not using an existingSecret.
  Shared by the Uptime Kuma deployment.
*/}}
{{- if not (or .Values.mysql.auth.existingSecret .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-credentials" (include "uptime-kuma.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if .Values.mysql.enabled }}
  db-password: {{ required "mysql.auth.password is required" .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
