{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptime-kuma.mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.mysql.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "uptime-kuma.mysql.fullname" . }}-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptime-kuma.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uptime-kuma.mysql.selectorLabels" . | nindent 8 }}
      annotations:
        # Changing auth values or config triggers a pod restart.
        # We checksum the values rather than the rendered secret (which uses
        # `include "file.yaml"` — not valid in Helm) to avoid re-rendering issues.
        checksum/secret: {{ toYaml .Values.mysql.auth | sha256sum }}
        checksum/config: {{ toYaml .Values.mysql.config | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mysql.podSecurityContext | nindent 8 }}
      initContainers:
        # Ensure the data directory is owned by the mysql user (UID/GID 65532 per dhi.io image spec).
        # Required for Longhorn and mandatory for NFS, where the Kubernetes
        # fsGroup mechanism is not honoured by the NFS server.
        - name: fix-data-dir-permissions
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              echo "Setting ownership of /var/lib/mysql and /run/mysqld to {{ .Values.mysql.securityContext.runAsUser }}:{{ .Values.mysql.securityContext.runAsGroup }}"
              mkdir -p /var/lib/mysql /run/mysqld
              chown -R {{ .Values.mysql.securityContext.runAsUser }}:{{ .Values.mysql.securityContext.runAsGroup }} /var/lib/mysql /run/mysqld
              chmod 750 /var/lib/mysql
              chmod 755 /run/mysqld
              # Remove lost+found if present — Longhorn/ext4 volumes create this
              # directory on the block device, which confuses MySQL's empty-datadir
              # check in the entrypoint script (ls -A returns non-empty).
              rm -rf /var/lib/mysql/lost+found
              echo "Done."
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
              add: [CHOWN, DAC_OVERRIDE, FOWNER]
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        # Write an init SQL file that ensures root@localhost has the correct
        # password. The dhi.io entrypoint creates root@'%' with the password
        # but leaves root@localhost (created by --initialize-insecure) without
        # one. We use --init-file to fix this on every startup idempotently.
        - name: write-init-sql
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              # Escape single quotes in password for SQL safety
              PW=$(echo "$MYSQL_ROOT_PASSWORD" | sed "s/'/\\\\'/g")
              cat > /init/init.sql <<EOF
              ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${PW}';
              ALTER USER 'root'@'%' IDENTIFIED WITH caching_sha2_password BY '${PW}';
              FLUSH PRIVILEGES;
              EOF
              echo "init.sql written."
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-kuma.mysql.secretName" . }}
                  key: mysql-root-password
          securityContext:
            runAsUser: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: mysql-init
              mountPath: /init
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.mysql.securityContext | nindent 12 }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-kuma.mysql.secretName" . }}
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-kuma.mysql.secretName" . }}
                  key: mysql-password
            {{- with .Values.mysql.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            # MYSQL_OPTIONS is appended verbatim to the mysqld command by the
            # dhi.io entrypoint script. Use it to pass flags the entrypoint
            # doesn't expose as dedicated env vars.
            - name: MYSQL_OPTIONS
              value: "--bind-address=0.0.0.0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=caching_sha2_password --init-file=/init/init.sql"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /init
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.mysql.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.mysql.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        - name: mysql-exporter
          image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
          args:
            - --mysqld.address=127.0.0.1:3306
            - --mysqld.username=root
            - --collect.info_schema.innodb_metrics
            - --collect.info_schema.query_response_time
          env:
            - name: MYSQLD_EXPORTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "uptime-kuma.mysql.secretName" . }}
                  key: mysql-root-password
          ports:
            - name: metrics
              containerPort: 9104
              protocol: TCP
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
        {{- end }}
      volumes:
        - name: mysql-init
          emptyDir: {}
        {{- if not .Values.mysql.persistence.enabled }}
        - name: mysql-data
          emptyDir: {}
        {{- end }}
      {{- with .Values.mysql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          {{- include "uptime-kuma.mysql.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- with .Values.mysql.persistence.annotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes:
          - {{ .Values.mysql.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size | quote }}
        {{- if .Values.mysql.persistence.storageClass }}
        {{- if (eq "-" .Values.mysql.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
